language: android
dist: trusty
sudo: required
jdk:
  - oraclejdk8
android:
  components:
    - tools
before_install:
  - echo y | android update sdk -u -a -t platform-tools
  - echo y | android update sdk -u -a -t build-tools-27.0.3
before_script:
  - curl https://kaltura.github.io/fe-tools/android/license.sh | sh
script:
  - ./gradlew mediaproviders:build
after_failure:
  - cat mediaproviders/build/reports/lint-results.xml
after_success:
  - ./travis-push-to-bintray.sh
notifications:
  email:
    recipients:
      - noam.tamim@kaltura.com
      - gilad.nadav@kaltura.com
    on_success: always
    on_failure: always

